### ISSUE TITLE
Cannot find module 'ws'

### ISSUE THREAD

**Issue by vvangxp** [onplus/shadowws#7]
运行 Server.js 时出现的提示，该怎么解决？

**Comment by vvangxp** [comment]
Debugger listening on [::]:15454
module.js:471
    throw err;
    ^

Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/environment/shadowws/server.js:13:15)
    at Object.<anonymous> (/home/ec2-user/environment/shadowws/server.js:230:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
